# -*- coding: utf-8 -*-
"""project2_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tU9PMl0K_NKUrVoMXDbSBZbdS_7bwIh1
"""

#!/usr/bin/python3
from mininet.topo import Topo

class Treetopo(Topo):
  def myNetwork(self):

    # Force OpenFlow13 and keep fail-mode secure so switches wait for ONOS
    L1 = self.addSwitch('L1')
    L2 = self.addSwitch('L2')
    L3 = self.addSwitch('L3')
    L4 = self.addSwitch('L4')
    s1 = self.addSwitch('s1')
    s2 = self.addSwitch('s2')

    h1 = self.addHost('h1')
    h2 = self.addHost('h2')
    h3 = self.addHost('h3')
    h4 = self.addHost('h4')
    h5 = self.addHost('h5')
    h6 = self.addHost('h6')
    h7 = self.addHost('h7')
    h8 = self.addHost('h8')

    self.addLink(h1, L1)
    self.addLink(h2, L1)
    self.addLink(h3, L2)
    self.addLink(h4, L2)
    self.addLink(h5, L3)
    self.addLink(h6, L3)
    self.addLink(h7, L4)
    self.addLink(h8, L4)

    self.addLink(L1, s1)
    self.addLink(L1, s2)
    self.addLink(L2, s1)
    self.addLink(L2, s2)
    self.addLink(L3, s1)
    self.addLink(L3, s2)
    self.addLink(L4, s1)
    self.addLink(L4, s2)

topos = {'mytopo':(lambda: TreeTopo())}